name: Publish package

on:
  push:
    branches:
      - main
    paths:
      - lib/**

permissions:
  contents: read # This is required for actions/checkout

jobs:
  publish-package:
    name: Publish Package
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - name: Use Node.js 16
        timeout-minutes: 1
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com
          scope: '@prafed'

      - name: Install dependencies
        run: yarn install --immutable
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - name: Bump patch version
        run: |
          npm version patch -m "Updated package version to  %s"

      - name: Release new version
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      # - name: Updated packages
      #   run: |
      #     npx lerna updated

      # - name: Version packages
      #   run: |
      #     npx lerna version --no-private --create-release github --message "chore(release): publish [skip ci]" --conventional-commits --yes
      #   env:
      #     GH_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      # - name: Publish packages
      #   run: npx lerna publish from-git --yes --no-verify-access
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
